AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:

  #---------------------------------------------------------------
  # DynamoDB tables
  #---------------------------------------------------------------
  myDB:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Users
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
  #---------------------------------------------------------------

  myCart:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Carts
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: serviceId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: serviceId
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
  #---------------------------------------------------------------

  myServices:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Services
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
  #---------------------------------------------------------------

  BarberLog:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: BarbersLog
      AttributeDefinitions:
        - AttributeName: date
          AttributeType: S
        - AttributeName: barberId
          AttributeType: S
      KeySchema:
        - AttributeName: date
          KeyType: HASH
        - AttributeName: barberId
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
  #---------------------------------------------------------------

  myBookings:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Bookings
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: serviceId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: serviceId
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
  #---------------------------------------------------------------

  myCoupons:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Coupons
      AttributeDefinitions:
        - AttributeName: name
          AttributeType: S
        - AttributeName: serviceId
          AttributeType: S
      KeySchema:
        - AttributeName: name
          KeyType: HASH
        - AttributeName: serviceId
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
  #---------------------------------------------------------------

  StockImage:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Stock
      AttributeDefinitions:
        - AttributeName: type
          AttributeType: S
        - AttributeName: name
          AttributeType: S
      KeySchema:
        - AttributeName: type
          KeyType: HASH
        - AttributeName: name
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
  #---------------------------------------------------------------

  Offers:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Offers
      AttributeDefinitions:
        - AttributeName: serviceId
          AttributeType: S
        - AttributeName: name
          AttributeType: S
      KeySchema:
        - AttributeName: serviceId
          KeyType: HASH
        - AttributeName: name
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
  #---------------------------------------------------------------



            
  